Traceback (most recent call last):
  File "streams_err.py", line 3, in <module>
    raise ValueError('Now we generate an error to STDERR')
ValueError: Now we generate an error to STDERR
